# Generated by Django 5.1.3 on 2024-11-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, upload_to='topic_images/'),
        ),
    ]
